config/routes.rb
Rails.application.routes.draw do
  root 'stats#index'

  resources :workers, only: %i[create destroy]

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  def create
    Workers.start
    worker_id = get_worker_id(action_type)
    Records::Create::Worker.perform_async(worker_id) if action_type == 'create'
    Records::Update::Worker.perform_async(worker_id) if action_type == 'update'

    redirect_to(root_path)
  end

  def destroy
    Workers.stop
  end

  private

  def action_type
    params.require(:action_type)
  end

  def get_worker_id(action_type)
    count = App.redis.hget(:worker_count, action_type) || 0
    worker_id = count.to_i + 1
    App.redis.hset(:worker_count, action_type, worker_id)
    "#{action_type}_#{worker_id}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stats/index.html.erb
<div><%= link_to 'Sidekiq', '/sidekiq' %></div>

<%= form_with(url: workers_path(action_type: :create)) do %>
  <%= submit_tag 'Spawn Create worker' %>
<% end %>

<%= form_with(url: workers_path(action_type: :update)) do %>
  <%= submit_tag 'Spawn Update worker' %>
<% end %>

<div>Records: <%= Record.count %></div>
<div>Create Workers: <%= App.redis.hget(:worker_count, :create) || 0 %></div>
<div>Update Workers: <%= App.redis.hget(:worker_count, :update) || 0 %></div>
<div>Sidekiq Errors: <%= Sidekiq::Failures.count %></div>